### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [jandraor/readsdr#7]
@jandraor: This package does not terminate its checks when run with the release candidate for igraph 2.0.0.

Is this a problem in your package? Should we be doing things differently?

Install the 2.0.0 release candidate using `pak::pak("igraph/rigraph")` .

We're planning to release igraph 2.0.0 on January 23. My sincere apologies for the short notice, I only realized today that I should have warned about the problem much earlier. Happy to postpone if it turns out that the problem is on our end. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by jandraor** [comment]
Hi, 

When I type `pak::pak("igraph/rigraph")`

I get the following:

Failed to build igraph 1.99.99.9000                           
Error:                                                          
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package igraph.
Type .Last.error to see the more details.

When I type `.Last.error`, I get this:

<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package igraph.
---
Backtrace:
1. pak::pak("igraph/rigraph")
2. pak::pkg_install(pkg, ...)
3. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …
4. err$throw(res$error)
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("pkg_install_do_plan", asNamespace("pak"))(...)
 3. proposal$install()
 4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
 5. base::withCallingHandlers({ …
 6. pkgdepends:::handle_events(state, events)
 7. pkgdepends:::handle_event(state, i)
 8. pkgdepends:::stop_task(state, worker)
 9. pkgdepends:::stop_task_build(state, worker)
10. base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …
11. | base::signalCondition(cond)
12. global (function (e) … 

Any ideas?

**Comment by krlmlr** [comment]
@gaborcsardi: Is there a way with pak to see why the build has failed?

```
## <callr_error/rlib_error_3_0/rlib_error/error>
Error:
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package igraph.

Backtrace:
1. pak::pak("igraph/rigraph")
2. pak::pkg_install(pkg, ...)
3. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …
4. err$throw(res$error)

Subprocess backtrace:
1. base::withCallingHandlers(cli_message = function(msg) { …
2. get("pkg_install_do_plan", asNamespace("pak"))(...)
3. proposal$install()
4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
5. base::withCallingHandlers({ …
6. pkgdepends:::handle_events(state, events)
7. pkgdepends:::handle_event(state, i)
8. pkgdepends:::stop_task(state, worker)
9. pkgdepends:::stop_task_build(state, worker)
10. base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …
11. | base::signalCondition(cond)
12. global (function (e) …
```

@jandraor: You could also try installing from r-universe: https://igraph.r-universe.dev/igraph# .

**Comment by jandraor** [comment]
@krlmlr 

I tried https://igraph.r-universe.dev/igraph#  & it worked.

I found where the issue is:

[vignettes/Introduction_to_readsdr.Rmd](https://github.com/jandraor/readsdr/blob/master/vignettes/Introduction_to_readsdr.Rmd)

It works fine if I run the code from Rstudio (click Run). However, when I click "knit", it gets stuck running this chunk:

```
library(igraph)

gr <- graph_from_data_frame(mdl$graph_dfs$edges, directed = TRUE, 
                               vertices = mdl$graph_dfs$nodes)

V(gr)$shape <- ifelse(V(gr)$type == "stock", "rectangle", "circle")

plot.igraph(gr, edge.arrow.size = 0.25,
            vertex.label.cex = 1, layout = layout.lgl(gr))
```

The issue is between the process that renders the vignette and igraph.

**Comment by krlmlr** [comment]
Thanks, weird. Could it be a random seed issue? I tried "knit" ten times in a row, works for me.

**Comment by krlmlr** [comment]
Now trying to plot in a loop 10000 times. Could you isolate the specific operation that is stuck?

**Comment by jandraor** [comment]
It's this one:

```
plot.igraph(gr, edge.arrow.size = 0.25,
            vertex.label.cex = 1, layout = layout.lgl(gr))
```

**Comment by krlmlr** [comment]
Thanks. It's weird that 10k iterations worked fine on my machine.

What OS are you on?

@szhorvat: Does this ring a bell -- `layout.lgl()` not terminating?

**Comment by jandraor** [comment]
macOS 13.5.1

**Comment by szhorvat** [comment]
> @szhorvat: Does this ring a bell -- `layout.lgl()` not terminating?

No, I don't recall seeing this. But the LGL layout is not getting a lot of love. Unless it produces something that's clearly better here, I would recommend using a different layout.

If you stick with LGL, note that `layout.lgl()` is deprecated. It is replaced by `layout_with_lgl()`.

If you do manage to produce a specific example (or seed) where it doesn't terminate, let us know and I'll look into it on the C/igraph side.

**Comment by krlmlr** [comment]
I can confirm the same behavior after installing igraph from r-universe. I'm really confused why this only occurs when called from knitr.

**Comment by krlmlr** [comment]
It's interesting that just drawing a single random number before computing the layout makes the problem go away.

@szhorvat: Can you replicate?

1. Install readsdr from CRAN, and igraph from r-universe, `install.packages("https://igraph.r-universe.dev/bin/macosx/big-sur-arm64/contrib/4.3/igraph_1.99.99.9000.tgz", repos = NULL)`
2. Render https://github.com/cran/readsdr/blob/master/vignettes/Introduction_to_readsdr.Rmd

I'm using the following code for the final chunk:

`````

```{r igraph}
library(igraph)

gr <- graph_from_data_frame(mdl$graph_dfs$edges, directed = TRUE, 
                               vertices = mdl$graph_dfs$nodes)

V(gr)$shape <- ifelse(V(gr)$type == "stock", "rectangle", "circle")

# The problem goes away when enabling this
# sample.int(1)
```

```{r layout}
layout <- layout.lgl(gr)
```

```{r plot, fig.align='center', fig.height=7, fig.width=7, message=FALSE, warning=FALSE}
plot.igraph(gr, edge.arrow.size = 0.25,
            vertex.label.cex = 1, layout = layout)
```
`````

**Comment by szhorvat** [comment]
I just made a fix in the C core, which is _likely not related_, but please update the C core just in case ... https://github.com/igraph/igraph/commit/fb82a46e36cf9bf4851b6d17a58e4653b8769ad5 This makes sure that the RNG state is saved/restored correctly. This is a specific requirement for R that I don't fully understand.

**Comment by krlmlr** [comment]
https://github.com/igraph/rigraph/pull/1129 might fix this issue.

@jandraor: can you please retry once this PR has reached r-universe, likely in ~4 hours?

**Comment by jandraor** [comment]
> [igraph/rigraph#1129](https://github.com/igraph/rigraph/pull/1129) might fix this issue.
> 
> @jandraor: can you please retry once this PR has reached r-universe, likely in ~4 hours?

It works.
